TARGET	= priv\sniff_winnt.dll
BUILD	= "$(MIX_BUILD_PATH)\lib\sniff\$(TARGET)"
SOURCES = src\sniff_winnt.c src\sniff.c
HEADERS = src\sniff.h
OBJDIR  = obj\winnt

all: $(BUILD)

$(TARGET): $(SOURCES) $(HEADERS)
	if not exist $(OBJDIR) mkdir $(OBJDIR)
	cl /W4 /LD /MD /I"$(ERTS_INCLUDE_DIR)" /Fo$(OBJDIR)\ /Fe$(TARGET) $(SOURCES)

$(BUILD): $(TARGET)
	copy $(TARGET) $(BUILD)

clean:
	del /q priv\sniff_winnt.*
	if exist $(OBJDIR) rd /s /q $(OBJDIR)
